### PR TITLE
[Fix]: Changed generate card token card id call 

### LINKED ISSUE #71: Payment fails with “10105 – BIN not found” error
Hi, Team! I’m calling the Mercado Pago Android SDK’s generateCardToken function to obtain a card token, but whenever I use that token to create a payment I receive a 400 response with error code 10105 – BIN not found. I’ve already created a test card in my account; below are all the details.

Function signature:
suspend fun generateCardToken(
    cardId: String,
    securityCodeState: PCIFieldState,
    expirationDateState: PCIFieldState? = null,
    buyerIdentification: BuyerIdentification
): Result<CardToken, ResultError>

My Code:

  val result = coreMethods.generateCardToken(
                        cardId = cardSelected.id.orEmpty(),
                        securityCodeState = cvvField.state,
                        buyerIdentification = BuyerIdentification(
                            name = "APRO"
                        )
                    )
                    when (result) {
                        is Result.Success -> {
                            Log.i("MercadoPago--", "success: " + result.data.toString())
                            val token = result.data.token
                            action?.onCardSelectedPayment(token)
                            bottomSheetDialog.dismiss()
                        }

                        is Result.Error -> {
                            when (result.error) {
                                is ResultError.Request -> {
                                    Log.i(
                                        "MercadoPago--", "request error: " + result.error.toString()
                                    )
                                }

                                is ResultError.Validation -> {
                                    Log.i(
                                        "MercadoPago--",
                                        "validation error: " + result.error.toString()
                                    )
                                }
                            }
                        }
                    }

Steps to reproduce:

1. Create a card via the Checkout API and associate it with your test user.
2. Copy the card’s id from the JSON response.
3. In your Android app, call:

val result = coreMethods.generateCardToken(
    cardId             = cardSelected.id.orEmpty(),    // In my case "1754573574648"
    securityCodeState  = cvvField.state,              // test CVV, "123"
    buyerIdentification= BuyerIdentification(name="APRO")
)

4. Inspect the Result.Success value to retrieve result.data.token (In my case, the function returns me 6a44f7ad1442d8e9d361373dc7bc73f7).
5. Send that token in a payment request.

Here you have my test card details:
{
  "additional_info": {
    "request_public": "true",
    "api_client_application": "traffic-layer",
    "api_client_scope": "mpapi-pci-tl"
  },
  "cardholder": {
    "name": "APRO",
    "identification": {
      "number": null,
      "type": null
    }
  },
  "customer_id": "2607165569-I9bQnhPSJca0aO",
  "date_created": "08/07/2025 08:32:53",
  "date_last_updated": "08/07/2025 08:32:53",
  "expiration_month": 11,
  "expiration_year": 2030,
  "first_six_digits": "547492",
  "id": "1754573574648",
  "issuer": {
    "id": 204,
    "name": "Mastercard"
  },
  "last_four_digits": "0366",
  "live_mode": false,
  "payment_method": {
    "id": "master",
    "name": "master",
    "payment_type_id": "credit_card",
    "thumbnail": "http://img.mlstatic.com/org-img/MP3/API/logos/master.gif",
    "secure_thumbnail": "https://www.mercadopago.com/org-img/MP3/API/logos/master.gif"
  },
  "security_code": {
    "length": 3,
    "card_location": "back"
  },
  "user_id": "2607165569"
}

Actual behavior:
Token generation succeeds and returns a value (e.g. 6a44f7ad1442d8e9d361373dc7bc73f7).
Using that token in a payment request always returns HTTP 400 with:

{
  "status": 400,
  "error": "10105-Bin not found"
}

Expected behavior:
The generated token should be valid for a purchase. No BIN not found error should occur when using a correctly generated token from the SDK.

Environment:
implementation(platform("com.mercadopago.android.sdk:sdk-android-bom:0.0.7"))
implementation("com.mercadopago.android.sdk:core-methods")
Android target: API 35 (Android 14)
Language: Kotlin

Question:
Is this a bug in the SDK’s tokenization process, or am I missing a required parameter/step in order to generate a valid token?

### PR DESCRIPTION
**Pull request by capaixao**
# Pull Request

## Checklist
- [ ] I have tested my changes creating a local version (More info in README file).
- [ ] I have added tests that prove my solution is effective and works
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Verify that you are merged with the latest in develop.
- [ ] I have run `./gradlew check` and fixed any possible issues of my code.
- [ ] I have tested my changes with configuration changes such as rotation, no conection, framework error handling
- [ ] I have tested the accessibility of the changes and added them to the screenshots.
- [ ] I have added a tag to the pull request that contains the product this pull request is related to.

### CODE REVIEW

File: core-methods/src/main/java/com/mercadopago/sdk/android/coremethods/domain/usecase/GenerateCardIdTokenUseCase.kt [hunk 1]
```diff
@@ -0,0 +1,64 @@
...
+        securityCode: String?,
+        expirationDate: String?,
+        buyerIdentification: BuyerIdentification? = null,
+    ): Result<CardToken, ResultError> {
+        if (cardId.isEmpty()) {
+            return Result.Error(ResultError.Validation("card id cannot be empty"))
+        }
+
+        if (!securityCode.isNullOrEmpty() && securityCode.length < SECURITY_CODE_MIN_LENGTH) {
+            return Result.Error(ResultError.Validation("security code length cannot be smaller than tree"))
```
Comment (diegomarcuz) [inline core-methods/src/main/java/com/mercadopago/sdk/android/coremethods/domain/usecase/GenerateCardIdTokenUseCase.kt]: Não seria melhor concatenar a constante na string do error? Não deixar hard coded

File: core-methods/src/main/java/com/mercadopago/sdk/android/coremethods/domain/usecase/GenerateCardIdTokenUseCase.kt [hunk 2]
```diff
@@ -0,0 +1,64 @@
...
+        var expirationMonth: Int? = null
+        var expirationYear: Int? = null
+
+        if (!expirationDate.isNullOrEmpty()) {
+            if (expirationDate.isEmpty()) {
+                return Result.Error(ResultError.Validation("expiration date cannot be empty"))
+            }
+
+            if (expirationDate.length < EXPIRATION_YEAR_MIN_LENGTH) {
+                return Result.Error(ResultError.Validation("expiration date length cannot be smaller than two"))
```
Comment (diegomarcuz) [inline core-methods/src/main/java/com/mercadopago/sdk/android/coremethods/domain/usecase/GenerateCardIdTokenUseCase.kt]: Mesma pergunta acima.

File: core-methods/src/main/java/com/mercadopago/sdk/android/coremethods/domain/usecase/GenerateCardIdTokenUseCase.kt [hunk 3]
```diff
@@ -0,0 +1,64 @@
...
+            }
+
+            expirationMonth = expirationDate.ifEmpty { "0" }.take(INT_TWO).toInt()
```
Comment (diegomarcuz) [inline core-methods/src/main/java/com/mercadopago/sdk/android/coremethods/domain/usecase/GenerateCardIdTokenUseCase.kt]: Porque usar esse fallback `ifEmpty` sendo que na linha 35 já faz uma garantia que não será vazio?

File: core-methods/src/main/java/com/mercadopago/sdk/android/coremethods/domain/usecase/GenerateCardTokenUseCase.kt [hunk 4]
```diff
@@ -9,58 +9,46 @@ import com.mercadopago.sdk.android.coremethods.domain.model.params.GenerateCardT
...
-            INT_ZERO
-        } else {
-            expirationDate?.ifEmpty { "0" }?.take(INT_TWO)?.toInt()
-        }
-        val expirationYear = if (expirationDateIsOptional) {
-            INT_ZERO
-        } else {
-            (EXPIRATION_YEAR_START + expirationDate?.ifEmpty { "0" }?.takeLast(INT_TWO)).toInt()
+        if (expirationDate.length < EXPIRATION_YEAR_MIN_LENGTH) {
+            return Result.Error(ResultError.Validation("expiration date length cannot be smaller than two"))
```
Comment (diegomarcuz) [inline core-methods/src/main/java/com/mercadopago/sdk/android/coremethods/domain/usecase/GenerateCardTokenUseCase.kt]: Mesma pergunta do outro arquivo sobre printar a constante

File: core-methods/src/main/java/com/mercadopago/sdk/android/coremethods/domain/usecase/GenerateCardTokenUseCase.kt [hunk 5]
```diff
@@ -9,58 +9,46 @@ import com.mercadopago.sdk.android.coremethods.domain.model.params.GenerateCardT
...
         }
 
+        val expirationMonth = expirationDate.ifEmpty { "0" }.take(INT_TWO).toInt()
```
Comment (diegomarcuz) [inline core-methods/src/main/java/com/mercadopago/sdk/android/coremethods/domain/usecase/GenerateCardTokenUseCase.kt:45]: Mesma pergunta do outro arquivo sobre o fallback.

**Review by francineemilia — DISMISSED** [review]

**Review by guilhermepratac — APPROVED** [review]

**Review by diegomarcuz — APPROVED** [review]

**Review by diegomarcuz — APPROVED** [review]
